#!/usr/bin/env bash

SOURCE_DIR="$(pwd)"
CMAKE_VERSION="3.6.1"

# Install dev tools
yum install -y deltarpm
yum update -y
yum remove -y cmake
yum install -y centos-release-scl
yum install -y "devtoolset-${GCC_VERSION}-gcc" "devtoolset-${GCC_VERSION}-gcc-c++"
yum install -y epel-release
yum install -y make openssl-devel libbsd-devel libuuid-devel zlib-devel

rm -rf build && mkdir build
curl -o build/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz -L https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
tar xf build/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz -C build
export CMAKE_INSTALL_PATH=${SOURCE_DIR}/build/cmake-${CMAKE_VERSION}-Linux-x86_64
export PATH="$PATH:$CMAKE_INSTALL_PATH/bin"

# Install Java
rpm --import http://repos.azulsystems.com/RPM-GPG-KEY-azulsystems
curl -o /etc/yum.repos.d/zulu.repo http://repos.azulsystems.com/rhel/zulu.repo
yum install -y zulu-8

# Run the build
export JAVA_HOME=/usr/lib/jvm/zulu-8
export BUILD_JAVA_HOME=${JAVA_HOME}
export BUILD_JAVA_VERSION=8
export GRADLE_OPTS="-Dorg.gradle.daemon=false"
scl enable "devtoolset-${GCC_VERSION}" -- "${SOURCE_DIR}/cppbuild/cppbuild" --c-warnings-as-errors --cxx-warnings-as-errors