#!/usr/bin/env bash

SOURCE_DIR="$(pwd)"

docker build --tag rhel-aeron \
  --build-arg USER_ID="$(id -u)" \
  --build-arg GROUP_ID="$(id -g)" \
  "${SOURCE_DIR}/cppbuild/rhel"

docker run --rm --shm-size=1G --network host \
  --volume="${SOURCE_DIR}":/opt/aeron \
  --volume="$(realpath ~/.gradle)":/home/athena/.gradle \
  rhel-aeron
