#!/usr/bin/env bash
##
## Copyright 2014-2019 Real Logic Ltd.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

AERON_BUILD_DIR=../../cppbuild/Release

export AERON_EVENT_LOG="0xffff"

case "`uname`" in
  Darwin* )
    export DYLD_FORCE_FLAT_NAMESPACE=1
    export DYLD_INSERT_LIBRARIES=${AERON_BUILD_DIR}/lib/libaeron_driver_agent.dylib
    ;;
  Linux*)
    export LD_PRELOAD=${AERON_BUILD_DIR}/lib/libaeron_driver_agent.so
    ;;
esac

${AERON_BUILD_DIR}/binaries/aeronmd
