#!/usr/bin/env bash
##
## Copyright 2016 Real Logic Ltd.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

version=`cat version.txt`

${JAVA_HOME}/bin/java \
    -cp aeron-samples/build/libs/samples.jar \
    -javaagent:aeron-agent/build/libs/aeron-agent-${version}-all.jar \
    -Daeron.event.log=admin,FRAME_IN \
    io.aeron.driver.MediaDriver
